# -*- coding: utf-8 -*-
# Generated by Django 4.2.7 on 2025-01-21 10:00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSession',
            fields=[
                ('device_id', models.CharField(max_length=128, primary_key=True, serialize=False, help_text='Device UUID')),
                ('notification_enabled', models.BooleanField(default=True, help_text='Whether notifications are enabled')),
                ('dark_mode_enabled', models.BooleanField(default=False, help_text='Whether dark mode is enabled')),
                ('preferred_language', models.CharField(default='en-US', max_length=5, help_text='Preferred language code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Device latitude', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Device longitude', max_digits=11, null=True)),
                ('location_updated_at', models.DateTimeField(blank=True, help_text='When location was last updated', null=True)),
                ('location_permission_granted', models.BooleanField(default=False, help_text='Whether location permission is granted')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the device session is active')),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time device was active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mobile Sessions',
                'db_table': 'mobile_device_sessions',
            },
        ),
        migrations.CreateModel(
            name='MobileAppUsage',
            fields=[
                ('usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_name', models.CharField(help_text='Name of the feature used', max_length=100)),
                ('feature_category', models.CharField(blank=True, help_text='Category of the feature', max_length=50)),
                ('usage_count', models.IntegerField(default=1, help_text='Number of times feature was used')),
                ('first_used', models.DateTimeField(default=django.utils.timezone.now, help_text='First time feature was used')),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time feature was used')),
                ('additional_data', models.JSONField(default=dict, help_text='Additional usage data')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='mobile_sessions.mobilesession', to_field='device_id')),
            ],
            options={
                'verbose_name_plural': 'Mobile App Usage',
                'db_table': 'mobile_device_usage',
                'unique_together': {('session', 'feature_name')},
            },
        ),
        migrations.AddIndex(
            model_name='mobilesession',
            index=models.Index(fields=['is_active'], name='mobile_dev_is_acti_e0d6d7_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilesession',
            index=models.Index(fields=['last_active_at'], name='mobile_dev_last_ac_be2b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilesession',
            index=models.Index(fields=['location_permission_granted'], name='mobile_dev_locatio_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilesession',
            index=models.Index(fields=['preferred_language'], name='mobile_dev_preferr_789abc_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileappusage',
            index=models.Index(fields=['session'], name='mobile_dev_session_456def_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileappusage',
            index=models.Index(fields=['feature_name'], name='mobile_dev_feature_789ghi_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileappusage',
            index=models.Index(fields=['feature_category'], name='mobile_dev_feature_cat_012jkl_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileappusage',
            index=models.Index(fields=['first_used'], name='mobile_dev_first_u_345mno_idx'),
        ),
    ]
