# Generated by Django 5.2.5 on 2025-08-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mobileappusage',
            new_name='mobile_devi_device__b7f94d_idx',
            old_name='mobile_dev_session_456def_idx',
        ),
        migrations.RenameIndex(
            model_name='mobileappusage',
            new_name='mobile_devi_feature_d5c975_idx',
            old_name='mobile_dev_feature_789ghi_idx',
        ),
        migrations.RenameIndex(
            model_name='mobileappusage',
            new_name='mobile_devi_feature_78b551_idx',
            old_name='mobile_dev_feature_cat_012jkl_idx',
        ),
        migrations.RenameIndex(
            model_name='mobileappusage',
            new_name='mobile_devi_first_u_3c06ea_idx',
            old_name='mobile_dev_first_u_345mno_idx',
        ),
        migrations.RenameIndex(
            model_name='mobilesession',
            new_name='mobile_devi_is_acti_20527c_idx',
            old_name='mobile_dev_is_acti_e0d6d7_idx',
        ),
        migrations.RenameIndex(
            model_name='mobilesession',
            new_name='mobile_devi_last_ac_6b5072_idx',
            old_name='mobile_dev_last_ac_be2b9b_idx',
        ),
        migrations.RenameIndex(
            model_name='mobilesession',
            new_name='mobile_devi_locatio_228e3a_idx',
            old_name='mobile_dev_locatio_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='mobilesession',
            new_name='mobile_devi_preferr_c75d7d_idx',
            old_name='mobile_dev_preferr_789abc_idx',
        ),
        migrations.AlterField(
            model_name='mobileappusage',
            name='session',
            field=models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='mobile_sessions.mobilesession'),
        ),
    ]
