# Generated by Django 5.2.5 on 2025-08-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_sessions', '0002_rename_mobile_dev_session_456def_idx_mobile_devi_device__b7f94d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilesession',
            name='game_high_score',
            field=models.IntegerField(default=0, help_text='Highest game score achieved in this session'),
        ),
    ]
