# Generated by Django 5.2.5 on 2025-08-14 06:09

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactType",
            fields=[
                (
                    "contact_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("type_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "contact_types",
            },
        ),
        migrations.CreateModel(
            name="County",
            fields=[
                ("county_id", models.AutoField(primary_key=True, serialize=False)),
                ("county_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Counties",
                "db_table": "counties",
            },
        ),
        migrations.CreateModel(
            name="OperationalStatus",
            fields=[
                (
                    "operational_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("status_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name_plural": "Operational Statuses",
                "db_table": "operational_statuses",
            },
        ),
        migrations.CreateModel(
            name="OwnerType",
            fields=[
                ("owner_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("type_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "owner_types",
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "service_category_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("category_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Service Categories",
                "db_table": "service_categories",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=200)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Constituency",
            fields=[
                (
                    "constituency_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("constituency_name", models.CharField(max_length=100)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constituencies",
                        to="facilities.county",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Constituencies",
                "db_table": "constituencies",
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                ("facility_id", models.AutoField(primary_key=True, serialize=False)),
                ("facility_name", models.CharField(max_length=200)),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("active_status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_facilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_facilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operational_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facilities",
                        to="facilities.operationalstatus",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Facilities",
                "db_table": "facilities",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="facilities.facility",
            ),
        ),
        migrations.CreateModel(
            name="FacilityCoordinate",
            fields=[
                ("coordinate_id", models.AutoField(primary_key=True, serialize=False)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                (
                    "coordinates_string",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("collection_date", models.DateField(auto_now_add=True)),
                (
                    "data_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "collection_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("active_status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinates",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "db_table": "facility_coordinates",
            },
        ),
        migrations.CreateModel(
            name="FacilityOwner",
            fields=[
                ("owner_id", models.AutoField(primary_key=True, serialize=False)),
                ("owner_name", models.CharField(max_length=200)),
                ("active_status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="facilities.facility",
                    ),
                ),
                (
                    "owner_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facilities.ownertype",
                    ),
                ),
            ],
            options={
                "db_table": "facility_owners",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "session_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_sessions",
            },
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                ("ward_id", models.AutoField(primary_key=True, serialize=False)),
                ("ward_name", models.CharField(max_length=100)),
                (
                    "constituency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wards",
                        to="facilities.constituency",
                    ),
                ),
            ],
            options={
                "db_table": "wards",
            },
        ),
        migrations.CreateModel(
            name="UserLocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facilities.ward",
                    ),
                ),
            ],
            options={
                "db_table": "user_locations",
            },
        ),
        migrations.AddField(
            model_name="facility",
            name="ward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="facilities",
                to="facilities.ward",
            ),
        ),
        migrations.CreateModel(
            name="FacilityContact",
            fields=[
                ("contact_id", models.AutoField(primary_key=True, serialize=False)),
                ("contact_value", models.CharField(max_length=255)),
                ("active_status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facilities.contacttype",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "db_table": "facility_contacts",
                "unique_together": {("facility", "contact_type", "contact_value")},
            },
        ),
        migrations.CreateModel(
            name="FacilityService",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                ("service_description", models.TextField(blank=True, null=True)),
                ("active_status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="facilities.facility",
                    ),
                ),
                (
                    "service_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facilities.servicecategory",
                    ),
                ),
            ],
            options={
                "db_table": "facility_services",
                "unique_together": {("facility", "service_category")},
            },
        ),
    ]
