# Generated by Django 4.2.8 on 2025-08-14 14:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Access Levels',
                'db_table': 'access_levels',
            },
        ),
        migrations.CreateModel(
            name='AuthenticationMethod',
            fields=[
                ('auth_id', models.AutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Authentication Methods',
                'db_table': 'authentication_methods',
            },
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('constituency_id', models.AutoField(primary_key=True, serialize=False)),
                ('constituency_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
                'db_table': 'constituencies',
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('contact_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'contact_types',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.AutoField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'db_table': 'counties',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('document_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Document Types',
                'db_table': 'document_types',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('dispensary', 'Dispensary'), ('health_center', 'Health Center'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('police_station', 'Police Station'), ('police_post', 'Police Post'), ('security_office', 'Security Office'), ('cbo', 'Community-Based Organization (CBO)'), ('ngo', 'Non-Governmental Organization (NGO)'), ('faith_based', 'Faith-Based Organization'), ('safe_house', 'Safe House'), ('shelter', 'Shelter'), ('legal_aid', 'Legal Aid Center'), ('gender_desk', 'Gender Desk'), ('counseling_center', 'Counseling Center'), ('rehabilitation_center', 'Rehabilitation Center'), ('community_center', 'Community Center'), ('youth_center', 'Youth Center'), ('women_center', 'Women Center'), ('elderly_center', 'Elderly Center'), ('disability_center', 'Disability Center')], max_length=30)),
                ('ownership', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('faith_based', 'Faith-based'), ('ngo', 'NGO'), ('community', 'Community-owned'), ('government', 'Government')], max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('location', models.CharField(help_text='Street address or general location description', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate (e.g., -1.2921)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate (e.g., 36.8219)', max_digits=9, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('target_population', models.CharField(blank=True, help_text='Primary target population served', max_length=200)),
                ('services_offered', models.TextField(blank=True, help_text='Brief description of main services')),
                ('operating_hours', models.CharField(blank=True, max_length=100)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_facilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GbvCategory',
            fields=[
                ('gbv_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'GBV Categories',
                'db_table': 'gbv_categories',
            },
        ),
        migrations.CreateModel(
            name='OperationalStatus',
            fields=[
                ('operational_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Operational Statuses',
                'db_table': 'operational_statuses',
            },
        ),
        migrations.CreateModel(
            name='OwnerType',
            fields=[
                ('owner_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'owner_types',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('service_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'db_table': 'service_categories',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.AutoField(primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=100)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='facilities.constituency')),
            ],
            options={
                'db_table': 'wards',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.ward')),
            ],
            options={
                'db_table': 'user_locations',
            },
        ),
        migrations.CreateModel(
            name='ResetToken',
            fields=[
                ('reset_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reset Tokens',
                'db_table': 'reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='FacilityOwner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=200)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners_new', to='facilities.facility')),
                ('owner_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.ownertype')),
            ],
            options={
                'db_table': 'facility_owners',
            },
        ),
        migrations.CreateModel(
            name='FacilityCoordinate',
            fields=[
                ('coordinate_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('coordinates_string', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_date', models.DateField(auto_now_add=True)),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_method', models.CharField(blank=True, max_length=100, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='facilities.facility')),
            ],
            options={
                'db_table': 'facility_coordinates',
            },
        ),
        migrations.CreateModel(
            name='FacilityContact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_value', models.CharField(max_length=255)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.contacttype')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_new', to='facilities.facility')),
            ],
            options={
                'db_table': 'facility_contacts',
                'unique_together': {('facility', 'contact_type', 'contact_value')},
            },
        ),
        migrations.CreateModel(
            name='Facility_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('curative', 'Curative Services'), ('preventive', 'Preventive Services'), ('diagnostic', 'Diagnostic Services'), ('rehabilitative', 'Rehabilitative Services'), ('support', 'Support Services'), ('security', 'Security Services'), ('legal', 'Legal Services'), ('counseling', 'Counseling Services'), ('protection', 'Protection Services'), ('education', 'Education Services'), ('training', 'Training Services'), ('advocacy', 'Advocacy Services'), ('emergency', 'Emergency Services'), ('referral', 'Referral Services')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Services',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility_Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('equipment_name', models.CharField(help_text='Name of the equipment or vehicle (e.g., Ambulance, Emergency Radio)', max_length=200)),
                ('category', models.CharField(choices=[('ambulance', 'Ambulance'), ('emergency_vehicle', 'Emergency Vehicle'), ('medical_transport', 'Medical Transport Vehicle'), ('police_vehicle', 'Police Vehicle'), ('security_vehicle', 'Security Vehicle'), ('medical_equipment', 'Medical Equipment'), ('diagnostic_equipment', 'Diagnostic Equipment'), ('emergency_equipment', 'Emergency Equipment'), ('first_aid_equipment', 'First Aid Equipment'), ('communication_equipment', 'Communication Equipment'), ('radio_equipment', 'Radio Equipment'), ('emergency_communication', 'Emergency Communication'), ('security_equipment', 'Security Equipment'), ('surveillance_equipment', 'Surveillance Equipment'), ('safety_equipment', 'Safety Equipment'), ('it_equipment', 'IT Equipment'), ('office_equipment', 'Office Equipment'), ('data_management', 'Data Management Equipment'), ('power_equipment', 'Power Equipment'), ('water_equipment', 'Water Equipment'), ('generator', 'Generator'), ('backup_systems', 'Backup Systems'), ('furniture', 'Furniture'), ('storage_equipment', 'Storage Equipment'), ('maintenance_equipment', 'Maintenance Equipment')], max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units available')),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('non_functional', 'Non-Functional'), ('under_maintenance', 'Under Maintenance')], default='good', max_length=20)),
                ('registration_number', models.CharField(blank=True, help_text='Vehicle registration number if applicable', max_length=50)),
                ('model_year', models.PositiveIntegerField(blank=True, help_text='Year of manufacture', null=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, help_text='Insurance expiry date for vehicles', null=True)),
                ('fuel_type', models.CharField(blank=True, help_text='Fuel type for vehicles (e.g., Petrol, Diesel, Electric)', max_length=20)),
                ('capacity', models.CharField(blank=True, help_text='Capacity or specifications (e.g., 4 passengers, 1000W)', max_length=50)),
                ('is_operational', models.BooleanField(default=True, help_text='Whether the equipment is currently operational')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the equipment')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Infrastructure',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility_HumanResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('staff_category', models.CharField(choices=[('medical', 'Medical Staff'), ('nursing', 'Nursing Staff'), ('pharmacy', 'Pharmacy Staff'), ('laboratory', 'Laboratory Staff'), ('police', 'Police Officers'), ('security', 'Security Personnel'), ('legal', 'Legal Staff'), ('counselor', 'Counselors'), ('social_worker', 'Social Workers'), ('psychologist', 'Psychologists'), ('administrative', 'Administrative Staff'), ('support', 'Support Staff'), ('volunteer', 'Volunteers')], max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Human Resources',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='operational_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='facilities.operationalstatus'),
        ),
        migrations.AddField(
            model_name='facility',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_facilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facility',
            name='ward_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='facilities.ward'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_url', models.URLField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='facilities.documenttype')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='facilities.facility')),
                ('gbv_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='facilities.gbvcategory')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='ContactClick',
            fields=[
                ('click_id', models.AutoField(primary_key=True, serialize=False)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('helpful', models.BooleanField(default=False)),
                ('followup_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='facilities.facilitycontact')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_clicks', to='facilities.facility')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_clicks', to='facilities.usersession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contact Clicks',
                'db_table': 'contact_clicks',
            },
        ),
        migrations.AddField(
            model_name='constituency',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='facilities.county'),
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='facilities.usersession')),
            ],
            options={
                'verbose_name_plural': 'API Tokens',
                'db_table': 'api_tokens',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='UserAuthMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.authenticationmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Authentication Methods',
                'db_table': 'user_auth_methods',
                'unique_together': {('user', 'auth_method')},
            },
        ),
        migrations.CreateModel(
            name='UserAccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.accesslevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Access Levels',
                'db_table': 'user_access_levels',
                'unique_together': {('user', 'access_level')},
            },
        ),
        migrations.CreateModel(
            name='FacilityService',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_new', to='facilities.facility')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.servicecategory')),
            ],
            options={
                'db_table': 'facility_services',
                'unique_together': {('facility', 'service_category')},
            },
        ),
        migrations.CreateModel(
            name='FacilityGbvCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('gbv_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.gbvcategory')),
            ],
            options={
                'verbose_name_plural': 'Facility GBV Categories',
                'db_table': 'facility_gbv_categories',
                'unique_together': {('facility', 'gbv_category')},
            },
        ),
    ]
