# Generated by Django 4.2.8 on 2025-08-14 19:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('operational_status', models.ForeignKey(blank=True, db_column='operational_status_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.operationalstatus')),
                ('ward', models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.ward')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='FacilityService',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_description', models.TextField(blank=True)),
                ('facility', models.ForeignKey(db_column='facility_id', on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('service_category', models.ForeignKey(blank=True, db_column='service_category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.servicecategory')),
            ],
            options={
                'verbose_name_plural': 'Facility Services',
                'db_table': 'facility_services',
            },
        ),
        migrations.CreateModel(
            name='FacilityOwner',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=200)),
                ('facility', models.ForeignKey(db_column='facility_id', on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('owner_type', models.ForeignKey(blank=True, db_column='owner_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.ownertype')),
            ],
            options={
                'verbose_name_plural': 'Facility Owners',
                'db_table': 'facility_owners',
            },
        ),
        migrations.CreateModel(
            name='FacilityCoordinate',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('coordinate_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('coordinates_string', models.CharField(blank=True, max_length=100)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100)),
                ('collection_method', models.CharField(blank=True, max_length=100)),
                ('facility', models.ForeignKey(db_column='facility_id', on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Coordinates',
                'db_table': 'facility_coordinates',
            },
        ),
        migrations.CreateModel(
            name='FacilityContact',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_value', models.CharField(max_length=200)),
                ('contact_type', models.ForeignKey(blank=True, db_column='contact_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.contacttype')),
                ('facility', models.ForeignKey(db_column='facility_id', on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Contacts',
                'db_table': 'facility_contacts',
            },
        ),
        migrations.CreateModel(
            name='FacilityGBVCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(db_column='facility_id', on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('gbv_category', models.ForeignKey(blank=True, db_column='gbv_category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.gbvcategory')),
            ],
            options={
                'db_table': 'facility_gbv_categories',
                'unique_together': {('facility', 'gbv_category')},
            },
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['ward'], name='facilities_ward_id_93b6d2_idx'),
        ),
    ]
