# Generated by Django 4.2.8 on 2025-08-05 19:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('dispensary', 'Dispensary'), ('health_center', 'Health Center'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy')], max_length=20)),
                ('ownership', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('faith_based', 'Faith-based'), ('ngo', 'NGO')], max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Facility_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('curative', 'Curative Services'), ('preventive', 'Preventive Services'), ('diagnostic', 'Diagnostic Services'), ('rehabilitative', 'Rehabilitative Services'), ('support', 'Support Services')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Services',
            },
        ),
        migrations.CreateModel(
            name='Facility_Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('equipment_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('medical_equipment', 'Medical Equipment'), ('it_equipment', 'IT Equipment'), ('utilities', 'Utilities'), ('furniture', 'Furniture'), ('vehicles', 'Vehicles')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(blank=True, max_length=50)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Infrastructure',
            },
        ),
        migrations.CreateModel(
            name='Facility_HumanResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('staff_category', models.CharField(choices=[('medical', 'Medical Staff'), ('nursing', 'Nursing Staff'), ('pharmacy', 'Pharmacy Staff'), ('laboratory', 'Laboratory Staff'), ('administrative', 'Administrative Staff'), ('support', 'Support Staff')], max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Human Resources',
            },
        ),
    ]
