# Generated by Django 5.2.5 on 2025-08-25 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('lookups', '0002_gbvcategory_icon_url_servicecategory_icon_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityinfrastructure',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_infrastructure_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilityinfrastructure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facilityinfrastructure',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_infrastructure_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='facilityinfrastructure',
            index=models.Index(fields=['is_active'], name='facility_in_is_acti_354d9a_idx'),
        ),
    ]
