# Generated by Django 4.2.8 on 2025-08-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='services_offered',
            field=models.TextField(blank=True, help_text='Brief description of main services'),
        ),
        migrations.AddField(
            model_name='facility',
            name='target_population',
            field=models.CharField(blank=True, help_text='Primary target population served', max_length=200),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('dispensary', 'Dispensary'), ('health_center', 'Health Center'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('police_station', 'Police Station'), ('police_post', 'Police Post'), ('security_office', 'Security Office'), ('cbo', 'Community-Based Organization (CBO)'), ('ngo', 'Non-Governmental Organization (NGO)'), ('faith_based', 'Faith-Based Organization'), ('safe_house', 'Safe House'), ('shelter', 'Shelter'), ('legal_aid', 'Legal Aid Center'), ('gender_desk', 'Gender Desk'), ('counseling_center', 'Counseling Center'), ('rehabilitation_center', 'Rehabilitation Center'), ('community_center', 'Community Center'), ('youth_center', 'Youth Center'), ('women_center', 'Women Center'), ('elderly_center', 'Elderly Center'), ('disability_center', 'Disability Center')], max_length=30),
        ),
        migrations.AlterField(
            model_name='facility',
            name='ownership',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('faith_based', 'Faith-based'), ('ngo', 'NGO'), ('community', 'Community-owned'), ('government', 'Government')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facility_humanresources',
            name='staff_category',
            field=models.CharField(choices=[('medical', 'Medical Staff'), ('nursing', 'Nursing Staff'), ('pharmacy', 'Pharmacy Staff'), ('laboratory', 'Laboratory Staff'), ('police', 'Police Officers'), ('security', 'Security Personnel'), ('legal', 'Legal Staff'), ('counselor', 'Counselors'), ('social_worker', 'Social Workers'), ('psychologist', 'Psychologists'), ('administrative', 'Administrative Staff'), ('support', 'Support Staff'), ('volunteer', 'Volunteers')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facility_infrastructure',
            name='category',
            field=models.CharField(choices=[('medical_equipment', 'Medical Equipment'), ('security_equipment', 'Security Equipment'), ('it_equipment', 'IT Equipment'), ('utilities', 'Utilities'), ('furniture', 'Furniture'), ('vehicles', 'Vehicles'), ('communication', 'Communication Equipment'), ('office_equipment', 'Office Equipment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facility_services',
            name='category',
            field=models.CharField(choices=[('curative', 'Curative Services'), ('preventive', 'Preventive Services'), ('diagnostic', 'Diagnostic Services'), ('rehabilitative', 'Rehabilitative Services'), ('support', 'Support Services'), ('security', 'Security Services'), ('legal', 'Legal Services'), ('counseling', 'Counseling Services'), ('protection', 'Protection Services'), ('education', 'Education Services'), ('training', 'Training Services'), ('advocacy', 'Advocacy Services'), ('emergency', 'Emergency Services'), ('referral', 'Referral Services')], max_length=20),
        ),
    ]
