# Generated by Django 4.2.8 on 2025-08-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_emergency_contact_facility_operating_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate (e.g., -1.2921)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate (e.g., 36.8219)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='location',
            field=models.CharField(help_text='Street address or general location description', max_length=200),
        ),
    ]
