# Generated by Django 4.2.23 on 2025-09-10 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities', '0002_facilityinfrastructure_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitycoordinate',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_coordinates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilitycoordinate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facilitycoordinate',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_coordinates_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='facilitycoordinate',
            index=models.Index(fields=['is_active'], name='facility_co_is_acti_b2f427_idx'),
        ),
    ]
