# Generated by Django 4.2.23 on 2025-09-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facilitycoordinate_created_by_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['facility_name'], name='facilities_facilit_0e2534_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['registration_number'], name='facilities_registr_5cd61b_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['ward', 'operational_status'], name='facilities_ward_id_28bb74_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['is_active', 'operational_status'], name='facilities_is_acti_36523b_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitycoordinate',
            index=models.Index(fields=['latitude', 'longitude'], name='facility_co_latitud_bdaf99_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitycoordinate',
            index=models.Index(fields=['is_active', 'latitude', 'longitude'], name='facility_co_is_acti_05a9aa_idx'),
        ),
    ]
