# Generated by Django 5.2.5 on 2025-08-21 12:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the music track', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the music track')),
                ('link', models.URLField(help_text='Link to the music file or streaming service', max_length=500)),
                ('artist', models.CharField(blank=True, help_text='Artist or creator of the music', max_length=200)),
                ('duration', models.DurationField(blank=True, help_text='Duration of the music track', null=True)),
                ('genre', models.CharField(blank=True, help_text='Genre of the music', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='music_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Music',
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='MusicPlay',
            fields=[
                ('play_id', models.AutoField(primary_key=True, serialize=False)),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_duration', models.DurationField(blank=True, help_text='How long the user listened to this track', null=True)),
                ('music', models.ForeignKey(db_column='music_id', on_delete=django.db.models.deletion.CASCADE, to='music.music')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Music Plays',
                'db_table': 'music_plays',
            },
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['is_active'], name='music_is_acti_040a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['genre'], name='music_genre_148897_idx'),
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['created_at'], name='music_created_88f77f_idx'),
        ),
        migrations.AddIndex(
            model_name='musicplay',
            index=models.Index(fields=['music'], name='music_plays_music_i_a83db1_idx'),
        ),
        migrations.AddIndex(
            model_name='musicplay',
            index=models.Index(fields=['user'], name='music_plays_user_id_4711ae_idx'),
        ),
        migrations.AddIndex(
            model_name='musicplay',
            index=models.Index(fields=['played_at'], name='music_plays_played__8346ff_idx'),
        ),
    ]
