# Generated by Django 5.2.5 on 2025-08-21 11:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('external_url', models.CharField(blank=True, max_length=500)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document_type', models.ForeignKey(db_column='document_type_id', on_delete=django.db.models.deletion.CASCADE, to='lookups.documenttype')),
                ('gbv_category', models.ForeignKey(blank=True, db_column='gbv_category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lookups.gbvcategory')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.CASCADE, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'indexes': [models.Index(fields=['document_type'], name='documents_documen_0426e4_idx'), models.Index(fields=['uploaded_by'], name='documents_uploade_f550b6_idx'), models.Index(fields=['is_public'], name='documents_is_publ_af3237_idx'), models.Index(fields=['is_active'], name='documents_is_acti_a803bb_idx')],
            },
        ),
    ]
