# Generated by Django 5.2.5 on 2025-08-25 21:41

import apps.common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Upload document file', null=True, upload_to=apps.common.utils.get_document_upload_path),
        ),
    ]
