# Generated by Django 4.2.8 on 2025-08-14 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('constituency_id', models.AutoField(primary_key=True, serialize=False)),
                ('constituency_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
                'db_table': 'constituencies',
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('contact_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Types',
                'db_table': 'contact_types',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.AutoField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'db_table': 'counties',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('document_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Document Types',
                'db_table': 'document_types',
            },
        ),
        migrations.CreateModel(
            name='GBVCategory',
            fields=[
                ('gbv_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'GBV Categories',
                'db_table': 'gbv_categories',
            },
        ),
        migrations.CreateModel(
            name='OperationalStatus',
            fields=[
                ('operational_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Operational Statuses',
                'db_table': 'operational_statuses',
            },
        ),
        migrations.CreateModel(
            name='OwnerType',
            fields=[
                ('owner_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Owner Types',
                'db_table': 'owner_types',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('service_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'db_table': 'service_categories',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.AutoField(primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=100)),
                ('constituency', models.ForeignKey(db_column='constituency_id', on_delete=django.db.models.deletion.CASCADE, to='common.constituency')),
            ],
            options={
                'verbose_name_plural': 'Wards',
                'db_table': 'wards',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.URLField()),
                ('uploaded_at', models.DateTimeField()),
                ('document_type', models.ForeignKey(blank=True, db_column='document_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.documenttype')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
