# Generated by Django 4.2.23 on 2025-09-10 05:42

import apps.common.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Hodi Admin', help_text='Application name displayed in browser title and branding', max_length=100)),
                ('site_tagline', models.CharField(default='Multi-Institutional GBV Response Platform', help_text='Tagline displayed under the site name', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Main application logo (recommended: 200x60px, PNG/SVG)', null=True, upload_to=apps.common.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'gif'])])),
                ('logo_alt_text', models.CharField(default='Hodi Admin Logo', help_text='Alt text for the logo image', max_length=100)),
                ('favicon', models.ImageField(blank=True, help_text='Favicon for browser tabs (recommended: 32x32px, ICO/PNG)', null=True, upload_to=apps.common.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'jpg', 'jpeg'])])),
                ('apple_touch_icon', models.ImageField(blank=True, help_text='Apple touch icon for mobile devices (recommended: 180x180px)', null=True, upload_to=apps.common.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('primary_color', models.CharField(default='#5e72e4', help_text='Primary brand color (hex code, e.g., #5e72e4)', max_length=7)),
                ('secondary_color', models.CharField(default='#8392ab', help_text='Secondary brand color (hex code, e.g., #8392ab)', max_length=7)),
                ('success_color', models.CharField(default='#2dce89', help_text='Success/positive action color (hex code, e.g., #2dce89)', max_length=7)),
                ('warning_color', models.CharField(default='#fb6340', help_text='Warning color (hex code, e.g., #fb6340)', max_length=7)),
                ('danger_color', models.CharField(default='#f5365c', help_text='Danger/error color (hex code, e.g., #f5365c)', max_length=7)),
                ('info_color', models.CharField(default='#11cdef', help_text='Info color (hex code, e.g., #11cdef)', max_length=7)),
                ('dark_color', models.CharField(default='#212529', help_text='Dark color for text and backgrounds (hex code, e.g., #212529)', max_length=7)),
                ('light_color', models.CharField(default='#f8f9fe', help_text='Light color for backgrounds (hex code, e.g., #f8f9fe)', max_length=7)),
                ('enable_dark_mode', models.BooleanField(default=False, help_text='Enable dark mode toggle for users')),
                ('default_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System)')], default='light', help_text='Default theme for new users', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Settings',
                'verbose_name_plural': 'Application Settings',
                'db_table': 'application_settings',
            },
        ),
    ]
