# Generated by Django 4.2.8 on 2025-08-14 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
        ('common', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='facility',
            field=models.ForeignKey(blank=True, db_column='facility_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='document',
            name='gbv_category',
            field=models.ForeignKey(blank=True, db_column='gbv_category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.gbvcategory'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='county',
            field=models.ForeignKey(db_column='county_id', on_delete=django.db.models.deletion.CASCADE, to='common.county'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['constituency'], name='wards_constit_b3144c_idx'),
        ),
        migrations.AddIndex(
            model_name='constituency',
            index=models.Index(fields=['county'], name='constituenc_county__9dc793_idx'),
        ),
    ]
