# Generated by Django 4.2.26 on 2025-11-27 09:46

import apps.common.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_add_apk_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='android_apk_url',
            field=models.URLField(blank=True, help_text='Direct download URL for APK (alternative to file upload)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='android_apk',
            field=models.FileField(blank=True, help_text='Android APK file for mobile app download', null=True, upload_to=apps.common.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['apk'])]),
        ),
    ]
