# Generated by Django 5.2.5 on 2025-08-21 11:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.AutoField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=100)),
                ('county_code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'db_table': 'counties',
                'indexes': [models.Index(fields=['county_name'], name='counties_county__94451a_idx'), models.Index(fields=['county_code'], name='counties_county__a59c4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('constituency_id', models.AutoField(primary_key=True, serialize=False)),
                ('constituency_name', models.CharField(max_length=100)),
                ('constituency_code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('county', models.ForeignKey(db_column='county_id', on_delete=django.db.models.deletion.CASCADE, to='geography.county')),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
                'db_table': 'constituencies',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.AutoField(primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=100)),
                ('ward_code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('constituency', models.ForeignKey(db_column='constituency_id', on_delete=django.db.models.deletion.CASCADE, to='geography.constituency')),
            ],
            options={
                'verbose_name_plural': 'Wards',
                'db_table': 'wards',
            },
        ),
        migrations.AddIndex(
            model_name='constituency',
            index=models.Index(fields=['county'], name='constituenc_county__9dc793_idx'),
        ),
        migrations.AddIndex(
            model_name='constituency',
            index=models.Index(fields=['constituency_name'], name='constituenc_constit_b8037d_idx'),
        ),
        migrations.AddIndex(
            model_name='constituency',
            index=models.Index(fields=['constituency_code'], name='constituenc_constit_e8225b_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['constituency'], name='wards_constit_b3144c_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['ward_name'], name='wards_ward_na_8e1694_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['ward_code'], name='wards_ward_co_61edb7_idx'),
        ),
    ]
