# Generated by Django 5.2.5 on 2025-08-21 11:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('audit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.BigIntegerField()),
                ('action_type', models.CharField(max_length=20)),
                ('event_category', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('severity_level', models.CharField(default='INFO', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.usersession')),
            ],
            options={
                'verbose_name_plural': 'Audit Trail',
                'db_table': 'audit_trail',
            },
        ),
        migrations.CreateModel(
            name='ContactInteraction',
            fields=[
                ('interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('user_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.ForeignKey(db_column='contact_id', on_delete=django.db.models.deletion.CASCADE, to='facilities.facilitycontact')),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.usersession', null=True, blank=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Interactions',
                'db_table': 'contact_interactions',
            },
        ),
    ]
