# Generated by Django 5.2.5 on 2025-08-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('mobile_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinteraction',
            name='device',
            field=models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='mobile_sessions.mobilesession', null=True, blank=True),
        ),
    ]
