# Generated by Django 5.2.5 on 2025-08-21 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_contactinteraction_device'),
        ('mobile_sessions', '0002_rename_mobile_dev_session_456def_idx_mobile_devi_device__b7f94d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinteraction',
            name='device',
            field=models.ForeignKey(blank=True, db_column='device_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile_sessions.mobilesession'),
        ),
    ]
