# Generated by Django 5.2.5 on 2025-08-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_contactinteraction_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinteraction',
            name='click_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contactinteraction',
            name='interaction_type',
            field=models.CharField(blank=True, default='general', max_length=50),
        ),
    ]
