# Generated by Django 4.2.8 on 2025-08-14 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('common', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.ward'),
        ),
        migrations.AddField(
            model_name='userauthmethod',
            name='auth_method',
            field=models.ForeignKey(db_column='auth_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.authenticationmethod'),
        ),
        migrations.AddField(
            model_name='userauthmethod',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.AddField(
            model_name='useraccesslevel',
            name='access_level',
            field=models.ForeignKey(db_column='access_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.accesslevel'),
        ),
        migrations.AddField(
            model_name='useraccesslevel',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='facility',
            field=models.ForeignKey(blank=True, db_column='facility_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='resettoken',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.AddField(
            model_name='contactclick',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facilitycontact'),
        ),
        migrations.AddField(
            model_name='contactclick',
            name='facility',
            field=models.ForeignKey(blank=True, db_column='facility_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='contactclick',
            name='session',
            field=models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.usersession'),
        ),
        migrations.AddField(
            model_name='contactclick',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='session',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.usersession'),
        ),
        migrations.AlterUniqueTogether(
            name='userauthmethod',
            unique_together={('user', 'auth_method')},
        ),
        migrations.AlterUniqueTogether(
            name='useraccesslevel',
            unique_together={('user', 'access_level')},
        ),
    ]
