# Generated by Django 5.2.5 on 2025-08-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='game_high_score',
            field=models.IntegerField(default=0, help_text='Highest game score achieved in this session'),
        ),
    ]
