# Generated by Django 5.2.5 on 2025-08-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_usersession_game_high_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(blank=True, default='/static/assets/img/brand/hodi app logo.png', max_length=500),
        ),
    ]
