# Generated by Django 5.2.5 on 2025-08-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionStatus',
            fields=[
                ('condition_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Condition Statuses',
                'db_table': 'condition_statuses',
                'indexes': [models.Index(fields=['status_name'], name='condition_s_status__6509be_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('contact_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('validation_regex', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Contact Types',
                'db_table': 'contact_types',
                'indexes': [models.Index(fields=['type_name'], name='contact_typ_type_na_65c398_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('document_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('allowed_extensions', models.CharField(max_length=255)),
                ('max_file_size_mb', models.IntegerField(default=10)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Document Types',
                'db_table': 'document_types',
                'indexes': [models.Index(fields=['type_name'], name='document_ty_type_na_0d5fea_idx')],
            },
        ),
        migrations.CreateModel(
            name='GBVCategory',
            fields=[
                ('gbv_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'GBV Categories',
                'db_table': 'gbv_categories',
                'indexes': [models.Index(fields=['category_name'], name='gbv_categor_categor_3ededf_idx')],
            },
        ),
        migrations.CreateModel(
            name='InfrastructureType',
            fields=[
                ('infrastructure_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Infrastructure Types',
                'db_table': 'infrastructure_types',
                'indexes': [models.Index(fields=['type_name'], name='infrastruct_type_na_52876f_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperationalStatus',
            fields=[
                ('operational_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Operational Statuses',
                'db_table': 'operational_statuses',
                'ordering': ['sort_order'],
                'indexes': [models.Index(fields=['status_name'], name='operational_status__0bbf1d_idx'), models.Index(fields=['sort_order'], name='operational_sort_or_617ed2_idx')],
            },
        ),
        migrations.CreateModel(
            name='OwnerType',
            fields=[
                ('owner_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Owner Types',
                'db_table': 'owner_types',
                'indexes': [models.Index(fields=['type_name'], name='owner_types_type_na_c589c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('service_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'db_table': 'service_categories',
                'indexes': [models.Index(fields=['category_name'], name='service_cat_categor_322cb1_idx')],
            },
        ),
    ]
