# Generated by Django 5.2.5 on 2025-08-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbvcategory',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to the icon for this GBV category', max_length=500),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to the icon for this service category', max_length=500),
        ),
    ]
