# Generated by Django 5.2.5 on 2025-08-25 10:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobile_sessions', '0003_mobilesession_game_high_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', help_text='Current status of the conversation', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the conversation', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Brief subject or topic of the conversation', max_length=200)),
                ('last_message', models.TextField(blank=True, help_text='Content of the last message sent')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Timestamp of the last message', null=True)),
                ('unread_count_mobile', models.IntegerField(default=0, help_text='Number of unread messages for mobile user')),
                ('unread_count_admin', models.IntegerField(default=0, help_text='Number of unread messages for admin')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_admin', models.ForeignKey(blank=True, help_text='Admin assigned to handle this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('last_message_by', models.ForeignKey(blank=True, help_text='User who sent the last message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_conversations', to=settings.AUTH_USER_MODEL)),
                ('mobile_session', models.ForeignKey(help_text='Mobile session that initiated the conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='mobile_sessions.mobilesession')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'emergency_chat_conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('mobile', 'Mobile User'), ('admin', 'Admin')], help_text='Type of sender', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice', 'Voice'), ('file', 'File'), ('location', 'Location')], default='text', help_text='Type of message content', max_length=20)),
                ('media_file', models.FileField(blank=True, help_text='Media file if message type is not text', null=True, upload_to='chat_files/%Y/%m/%d/')),
                ('media_url', models.URLField(blank=True, help_text='URL to media file if message type is not text')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', help_text='Delivery status of the message', max_length=20)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False, help_text='Whether this message is marked as urgent')),
                ('metadata', models.JSONField(default=dict, help_text='Additional message metadata (coordinates, file info, etc.)')),
                ('conversation', models.ForeignKey(help_text='Conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('sender', models.ForeignKey(blank=True, help_text='User who sent the message (null for mobile users)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'emergency_chat_messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_message', 'New Message'), ('conversation_assigned', 'Conversation Assigned'), ('urgent_message', 'Urgent Message'), ('conversation_resolved', 'Conversation Resolved')], help_text='Type of notification', max_length=30)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('body', models.TextField(help_text='Notification body')),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(help_text='User to receive the notification', on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(help_text='Related conversation', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.conversation')),
                ('message', models.ForeignKey(blank=True, help_text='Related message if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.message')),
            ],
            options={
                'verbose_name': 'Chat Notification',
                'verbose_name_plural': 'Chat Notifications',
                'db_table': 'emergency_chat_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status'], name='emergency_c_status_51cf71_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['priority'], name='emergency_c_priorit_4bd477_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['assigned_admin'], name='emergency_c_assigne_def626_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='emergency_c_created_6bac2d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='emergency_c_last_me_8a2ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation'], name='emergency_c_convers_facbbe_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='emergency_c_sender__568497_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_type'], name='emergency_c_sender__3b2a87_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sent_at'], name='emergency_c_sent_at_3a3fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status'], name='emergency_c_status_dc2d02_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_urgent'], name='emergency_c_is_urge_d9f777_idx'),
        ),
        migrations.AddIndex(
            model_name='chatnotification',
            index=models.Index(fields=['user'], name='emergency_c_user_id_611b40_idx'),
        ),
        migrations.AddIndex(
            model_name='chatnotification',
            index=models.Index(fields=['notification_type'], name='emergency_c_notific_98f949_idx'),
        ),
        migrations.AddIndex(
            model_name='chatnotification',
            index=models.Index(fields=['is_read'], name='emergency_c_is_read_7681b4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatnotification',
            index=models.Index(fields=['created_at'], name='emergency_c_created_cfae1d_idx'),
        ),
    ]
