# Generated by Django 5.2.5 on 2025-08-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL to media file if message type is not text (for external files)'),
        ),
    ]
