# Generated by Django 5.2.5 on 2025-08-25 21:41

import apps.common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, help_text='Media file if message type is not text', null=True, upload_to=apps.common.utils.get_chat_file_upload_path),
        ),
    ]
